name: R CMD check

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Run R CMD check
        run: R CMD check .
      - name: Say Hello from GSoC Test
        run: echo "🎉 Hello from Rperform Easy Test!"

